sudo: false
language: generic
matrix:
  include:
  - os: linux
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
  timeout: 3600
before_install:
- travis_wait 45 bash ./utilities/travis_setup.sh
- export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
script:
- latexmk -pdf -interaction=nonstopmode -halt-on-error manuscript.tex
after_success: 
deploy:
  provider: releases
  api_key:
    secure: r9A/eQWkv983nigGCLpxZD4V27NpgxRKCvUgwBfl+bWhYDGPBScNoiUSgK1jKdkJtr28zP2adiS94rT2asItR22+7TjmOLtQIS3aEUbPT5sPllzT6HTzS6lWtkY9Z5hfaxuUhg4Yp6xwjKy/bPxqz4I20r9d8bytqxe3E2ThwY+mVORQUXrCTpvVrm47G1ehClwYvF2IFnfuFXbetzKaST2A1/8xmOc/YehQAQuSPRZ16oGcHzSgT/RTL7O+kGm61xv02qqGTRmkHc9anK23oxXzl+dYn7BHr81cRmkdzCXeVTejvKBRAeIYE5BKZzgFgv2PY/gvBS69wUn6SAR0dbjVpFbyO2Toq2yE6yywPfHxEnfKwnAtN7fHk6vrAFTvR4FAdUwppl+BAbKgKEjQP0FQrc0uA8OEpsAuBzC+XPXMDgIPibqq6D2moUVntzYw55KN4DTNwgbFXXDnz0oOQfaOJzwIVCP3SvZp+onrvE1Br63ye8qA2nnIpHtY6Q1+oy47GW8lISExwi0ok62j586jD5fWb4XkjXFAQsbuwd+Sh5F/YP03NkRnQoEdAZuP0ehwlBY91/L0AbCT/fFr3x1WGD6hGrl2tHo8gUPCalJ5h8VZqzHBsrNkEfT8bvetEQhJmMjGzaDwLGZtAUNnyj7R8r6hyXh67gMPGKxUo/s=
  file: manuscript.pdf
  skip_cleanup: true
  on:
    repo: skulumani/2018_aas_manuscript
    tags: true

